print("Hello World")
print(type("Hello World"))
print(10)
print(type(10))
print(3.91)
print(type(3.91))
print(True)
print(type(True))
print(False)
print(type(False))
print(1+2j)
print(type(1+2j))
print(10+3.5)
print(type(10+3.5))